# Site settings
permalink: /blog/:categories/:year/:month/:day/:title.html
title: datajet - Personalized search and recommendation technologies
email: discovery@rocket-internet.de
description: > # this means to ignore newlines until "baseurl:"
  TODO
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: TODO
github_username:  TODO

# Build settings
markdown: kramdown
