# Page settings
baseurl = "http://datajet.io"
title = "datajet.io - Personalized Search and Recommendation Technologies"
languageCode = "en-us"
theme = "hugo-elate-theme"
[params]
  custom_css = []
  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "datajet"
    home = "Home"
    work = "Core Functionalities"
    testimonials = "Testimonials"
    services = "Services"
    about = "Team"
    contact = "Contact"
    # You can add custom links before or after the default links
    # Assign a weight to define the order
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10
    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  # Hero section
  [params.hero]
    title = "Discovery Delivery Platform"
    subtitle = 'Help your visitors discover products they love ❤ <br><br> Our machine-learning based Search and Recommendation technology provides tailored and optimized experience'
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  [[params.intro.item]]
    title = "Data"
    description = "Collecting events and analyzing data for user actions, preferences, and context like location, device."
    url = ""
    button = ""
    icon = ""
    img = "img_7.jpg"
  [[params.intro.item]]
    title = "Discovery Engine"
    description = "Providing real-time intelligent search and tailored recommendation backed by machine learning."
    url = ""
    button = ""
    icon = ""
    img = "img_8.jpg"
  [[params.intro.item]]
    title = "User Experience"
    description = "Helping users to discover what they are looking easily by smart search technologies and features."
    url = ""
    button = ""
    icon = ""
    img = "img_10.jpg"
  # Work section
  [params.work]
    enable = true
    title = "Core Functionalities"
    description = "Our service ensures that your shop system delivers lightning fast, relevant search results and leverages our recommendation system to boost your conversion rate. By using machine learning techniques, it automatically categorizes and ranks relevance of the products. <br><br> We believe in the power of data to help us identify the needs of your customers and that a better understanding of your customers' needs is critical to strengthening the relationship with your customer base."
    footertext = ''
  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Proudly used by the market leaders in e-commerce and fashion."
    [[params.testimonials.item]]
      quote = "&ldquo;Datajet has been an important partner in our personalization strategy. Our customers love the recommendations we provide to them along the shopping experience and the technology has proven to be a valuable revenue driver for ZALORA in South East Asia."
      person = 'Silvia Thom <span class="subtext">Director Product Management</span> <a href="https://worldwide.zalora.com/" target="_blank">ZALORA</a> '
      img = "silvia_thom.jpg"
      alt = "Silvia Thom"
    [[params.testimonials.item]]
      quote = "&ldquo;Global Fashion Group, the world’s leading online fashion destination for emerging markets, is glad to collaborate with Datajet for their ability to scale across our 24 countries and expertise to offer best in-class shopping experience for our customers."
      person = 'Isabelle Bénard <span class="subtext">Head of Product Management</span> <a href="http://global-fashion-group.com" target="_blank">Global Fashion Group</a> '
      img = "isabelle_benard.jpg"
      alt = "Isabelle Bénard"
    [[params.testimonials.item]]
      quote = "&ldquo;As a Latam's market leader in fashion e-commerce, Dafiti have the challenge to find the most relevant and personalized item for the customers. Datajet has been a valuable partner in providing us a fast and reliable search."
      person = 'Roosevelt Nascimento Junior <span class="subtext">Chief Product Officer</span> <a href="http://www.dafiti.com/" target="_blank">DAFITI</a> '
      img = "roosevelt_nascimento_junior.jpg"
      alt = "Roosevelt Nascimento Junior"
  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Our expertise in technology and data analytics has allowed us to build a system that enables you to create an engaging, personalized shopping experience and lasting customer satisfaction."
    [[params.services.item]]
      title = "Intelligent Search"
      description = "Machine-learning powered search built for web and app with custom and automated result rankings."
      icon = ""
    [[params.services.item]]
      title = "Autocomplete"
      description = "Enables users to quickly autocomplete their searches as they type, leveraging searching and filtering."
      icon = ""
    [[params.services.item]]
      title = "Recommendations"
      description = "Automatically tailor product recommendations to customer preference and business goals."
      icon = ""
      [[params.services.item]]
      title = "Visual Search"
      description = "Helping users to take a photo to discover products when words are not enough to describe."
      icon = ""
  # About section
  [params.about]
    enable = true
    title = "Team"
    description = "We are a passionate group of technologists with collective experience across leading technology and e-commerce companies."
    [[params.about.item]]
      name = "Serkan Baydin"
      position = "Head of Search"
      description = ""
      img = "serkan_baydin.jpg"
      alt = "Serkan"
    [[params.about.item]]
      name = "Igor Veremchuk"
      position = "Technical Lead"
      description = ""
      img = "igor_veremchuk.jpg"
      alt = "Igor"
    [[params.about.item]]
      name = "Cristian Angelini"
      position = "Senior Software Engineer"
      description = ""
      img = "cristian_angelini.jpg"
      alt = "Cristian"
    [[params.about.item]]
      name = "Naresh Venkateshappa"
      position = "Senior System Engineer"
      description = ""
      img = "naresh_venkateshappa.jpg"
      alt = "Naresh"
    [[params.about.item]]
      name = "Moath Almallahi"
      position = "Senior Software Engineer"
      description = ""
      img = "moath_almallahi.jpg"
      alt = "Moath"
    [[params.about.item]]
      name = "Waiting for you!"
      position = "New Talent!"
      description = ""
      img = "person1.jpg"
      alt = "You"
  # Contact section
  [params.contact]
    enable = true
    map = false
    form = false
    title = "Let's Get in touch"
    description = 'Power-up your conversion now! <br><br> Our machine-learning based search and recommendation technology lets your customers discover and find products they love. Optimize search and recommendation in your apps and desktop according to your business goals and customer preference. <br><br> <a href="mailto:team@datajet.io"> team@datajet.io </a>'
  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; datajet.io - All Rights Reserved.'

